---    
- name: Check the GDisk commands
  block:
      - name: Get output of current block
        shell: lsblk

      - name: Get more detailed output from gdisk
        shell: gdisk -l {{ vol_drive }}
        ignore_errors: true

  
- name: Create Partions
  block:

    ### 3: /var 10G
    ### 4:/var/log 5G
    ### 5:/var/tmp 2G
    ### 6:/var/log/audit 5G
    ### 7:/home 5G
    ### 8:/tmp 3G
    ### 9:/boot 1G
      - name: Create the new partitions
        shell: sgdisk -e -n 3:0:+{{ var_size | int }}G -n 4:0:+{{ log_size | int }}G -n 5:0:+{{ vtmp_size | int }}G -n 6:0:+{{ audit_size | int }}G -n 7:0:+{{ home_size | int }}G -n 8:0:+{{ tmp_size | int }}G -n 9:0:+{{ boot_size | int }}G -t 3:8300 -t 4:8300 -t 5:8300 -t 6:8300 -t 7:8300 -t 8:8300 -t 9:8300 {{ vol_drive }} -p
        become: yes
        become_method: sudo

      - name: Name the partitions
        shell: sgdisk -c 3:"var" -c 4:"log" -c 5:"vartmp" -c 6:"audit" -c 7:"home" -c 8:"tmp" -c 9:"boot" {{ vol_drive }} -p
        become: yes
        become_method: sudo

      - name: Update Partitions without reboot
        shell: partprobe {{ vol_drive }}
    
      - name: Show us our block after creating new partitions
        shell: lsblk

 
